      <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
        <div class="container">

          <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">
            <span class="navbar-toggler-icon "></span>
          </button>

          <a href="/" class="navbar-brand">
            <img src="img/logo.png" width="142">
          </a>

          <div class="collapse navbar-collapse" id="nav-principal">
            <ul class="navbar-nav ml-auto">
              <li>
                <a href="/" class="nav-link active">Home</a>
              </li>
              <li>
                <a href="/recursos" class="nav-link mr-4">Recursos</a>
              <li>
                <a href="/login" class="btn btn-outline-light ml-1">Entrar</a>
              </li>
              <li>
                <a href="/inscreverse" class="btn btn-outline-light ml-1">Cadastrar-se</a>
              </li>
              
            </ul>
            
          </div>

          
        </div>
        
      </nav>
    </header>

    <section class="" id="home"> <!--começo da home-->
      <div class="container"> 
        <div class="row">

          <div class="col-md-6 d-flex">
            <div class="align-self-center">
              <h1 class="display-4">
                Suas contas descomplicadas
              </h1>
              <p>
                Usado por mais de 1 milhão de pessoas, o Finans é uma ferramenta online que vai facilitar sua vida financeira.
              </p>
             
               
                  
           
                    <a href="/inscreverse" class="m-3 btn btn-primary btn-lg btn-block">Cadastrar-se</a>
                    


                  
              
              
              <p>
                Disponível para
                <a href="" class="btn btn-outline-dark">
                  <i class="fab fa-android fa-lg"></i>

                </a>
                <a href=" " class="btn btn-outline-dark">
                    <i class="fab fa-apple fa-lg"></i>
                </a>
              </p>
            </div>
          </div>
          <div class="col-md-6 d-none d-md-block">
            <img src="img/capa-mulher.png">
          </div>
      
        </div>
      </div>
    </section><!--fim da home-->

    <section class="espaçamento"><!--inicio de conteudos informativos-->
      <div class="container">
        <div class="row">

          <div class="col-md-6 d-flex">
            <div class="align-self-center">
              <h2>
                Saiba para onde vai o seu dinheiro
              </h2>
              <p>
                Com o Finans, você categoriza todos os seus lançamentos com gráficos simples, você sabe para onde vai o seu dinheiro.
              </p>
              <a href="/recursos" class="btn btn-primary">Veja mais...</a>
            </div>
          </div>

          <div class="col-md-6">
            <img src="img/saiba.png" class="img-fluid">
          </div>
          
        </div>
        
      </div>

    </section><!--fim de conteudos informativos-->

<section class="espaçamento"><!--inicio de conteudos informativos-->
      <div class="container">
        <div class="row">
          <div class="col-md-6">
               <img src="img/juros.png" class="img-fluid">
          </div>

          <div class="col-md-6 d-flex">
            <div class="align-self-center">
              <h2>
                Pare de pagar juros, economize!
              </h2>
              <p>
                Manter as contas em dia é sempre um problema? O finans avisa você: receba alertas de contas a pagar e a receber
              </p>
              <a href="/recursos" class="btn btn-primary">Veja mais...</a>
            </div>
          </div>

          
          
        </div>
        
      </div>

    </section><!--fim de conteudos informativos-->

    <section class="espaçamento mb-4"><!--inicio de conteudos informativos-->
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <img src="img/facil.png" class="img-fluid">
            <h4>
              Fácil de usar
            </h4>
            <p>
              O Finans vai além do básico e permite que você faça controles incríveis, essenciais para suas finanças. Simples como tem que ser! 
            </p> 
          </div> 

          <div class="col-md-4">
            <img src="img/economize.png" class="img-fluid">
            <h4>
              Economize seu tempo!
            </h4>
            <p>
              Tempo é dinheiro! Em segundos, você tem tudo sob controle e aproveite seu tempo com o que realmente importa para você!
            </p>
          </div> 

          <div class="col-md-4">
            <img src="img/suporte.png" class="img-fluid">
            <h4>
              Suporte amigo!
            </h4>
            <p>
              Dúvidas? Perguntas? Nosso suporte super legal ajuda você! A gente tá aqui para resolver seus problemas e deixas sua vida bem mais fácil! 
            </p>
          </div>         
        </div>
        
      </div>

    </section><!--fim de conteudos informativos-->

    <footer class="mt-4 mb-4">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <nav class="navbar navbar-expand-sm ">
              <ul class="text-dark" style="list-style: none;">
                <li>
                  <a href="#" class="nav-link text-dark">Home</a>
                </li>
                <li>
                  <a href="#" class="nav-link text-dark">Recursos</a>
                </li>
              </ul>
            </nav>
          </div>

          <div class="col-md-4  d-flex ">
            <div class="align-self-auto">
                  <a href="" class="btn btn-outline-dark">
                    <i class="fab fa-facebook fa-2x"></i>
                  </a>
                  <a href="" class="btn btn-outline-dark">
                    <i class="fab fa-twitter fa-2x"></i>
                  </a>
                  <a href="" class="btn btn-outline-dark">
                    <i class="fab fa-instagram fa-2x"></i>
                  </a>
                  <a href="" class="btn btn-outline-dark">
                    <i class="fab fa-youtube fa-2x"></i>
                  </a>
            </div>
          </div>
        </div>
        
      </div>
      
    </footer>

    <!-- JavaScript (Opcional) -->
    <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<?php
  
?>