<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center bg-primary p-3 mb-2 rounded-top">
          <img src="/img/logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
              <div class="form-group">
                <input type="text" minlength="3" required value="<?= $this->view->usuario['nome'] ?>" name="nome" class="form-control" placeholder="Nome">
              </div>
              
              <div class="form-group">
                <input type="text" minlength="3" required value="<?= $this->view->usuario['email'] ?>" name="email" class="form-control" placeholder="E-mail">
              </div>

              <div class="form-group">
                <input type="text" required value="<?= $this->view->usuario['celular'] ?>" name="celular" class="form-control" placeholder="(99) 99999-9999">
              </div>

              <div class="form-group">
                <input type="password" minlength="4" required value="<?= $this->view->usuario['senha'] ?>" name="senha" class="form-control" placeholder="Senha">
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>
              <a href="/" class="btn btn-primary btn-block">Voltar</a>

              <?php if($this->view->erroCadastro) {?>

                <small class="form-text text-danger">*Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidas novamente!*</small>

              <?php } ?>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>
