<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center bg-primary p-3 mb-2 rounded-top">
          <img src="/img/logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Login</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/autenticar" method="post">
              <div class="form-group ">
                <input type="text" value="" name="email" class="form-control" placeholder="E-mail" required>
              </div>
                <div classe="form-group">
                    <input type="password" value="" name="senha" class="form-control" placeholder="Senha" required>
                </div>
              
              
              <button type="submit" class="btn btn-primary btn-block mt-4 ">Entrar</button>
              <a href="/" class="btn btn-primary btn-block">Voltar</a>

              <?php if($this->view->erroCadastro) {?>

                <small class="form-text text-danger">*Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidas novamente!*</small>

              <?php } ?>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>