<nav class="navbar navbar-expand-sm navbar-dark bg-primary">
        <div class="container">

          <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">
            <span class="navbar-toggler-icon "></span>
          </button>

          <a href="/" class="navbar-brand">
            <img src="img/logo.png" width="142">
          </a>

          <div class="collapse navbar-collapse" id="nav-principal">
            <ul class="navbar-nav ml-auto">
              <li>
                <a href="/" class="nav-link">Home</a>
              </li>
              <li>
                <a href="/recursos" class="nav-link mr-4 active">Recursos</a>
              <li>
                <a href="/login" class="btn btn-outline-light ml-1">Entrar</a>
              </li>
              <li>
                <a href="/inscreverse" class="btn btn-outline-light ml-1">Cadastrar-se</a>
              </li>
              
            </ul>
            
          </div>

          
        </div>
        
      </nav>
    </header>

    <section class="mt-4 mb-4" id="home"> <!--começo da home-->

      <div class="container"> 
        <div class="row">

            <div class="col d-flex">
                <h1 class="display-3">Recursos e Melhorias da Aplicação</h1>
            </div>
        </div>
        <hr>
        <div class="row">
            
            <div class="col-6 ">
                <h5>Recursos da aplicação</h5>
                <img class="mt-4"src="/img/improvements.jpg" alt="thinking" width="460">
                
            </div>

            <div class="col-md-6 d-flex">
            <div class="accordion" id="accordionExample">
                <div class="card">
                    <div class="card-header bg-primary text-white" id="headingOne">
                    <h2 class="mb-0">
                        <button class="btn btn-primary btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Recursos da Aplicação
                        </button>
                    </h2>
                    </div>

                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                    <div class="card-body">
                        <ul >
                          <li class="list-unstyled"> <i class="fas fa-check text-success"></i> O aplicativo adiciona ganhos e despesas</li>
                          <li class="list-unstyled"><i class="fas fa-check text-success"></i> O aplicativo deleta ganhos e despesas</li>
                          <li class="list-unstyled"><i class="fas fa-check text-success"></i> O aplicativo faz cadastro de usuários</li>
                          <li class="list-unstyled"><i class="fas fa-check text-success"></i> O aplicativo tras o saldo atual</li>
                          <li class="list-unstyled"><i class="fas fa-check text-success"></i> O aplicativo tras por meio de gráficos o balanço de despesas e ganhos</li>
                          <li class="list-unstyled"><i class="fas fa-check text-success"></i> O aplicativo tras por meio de gráficos as despesas por categoria</li>
                        </ul>
                    </div>
                    </div>
                </div>
                <div class="card">
   
                </div>
                
            </div>
            
        </div>
      </div>
    </section><!--fim da home-->
    <section>
      <div class="container">
        <div class="row">
        <div class="col-md-6 ">
                <h5>Melhorias futuras para aplicação</h5>
                <img class="mt-4"src="/img/development.jpg" alt="thinking" width="460">
                
            </div>

            <div class="col-md-6 d-flex">
              <div class="accordion" id="accordionExample2">
                <div class="card ">
                    <div class="card-header bg-info" id="headingtwo">
                      <h2 class="mb-0">
                          <button class="btn btn-info btn-block text-left" type="button" data-toggle="collapse" data-target="#collapsetwo" aria-expanded="true" aria-controls="collapsetwo">
                            Melhorias futuras para aplicação
                          </button>
                      </h2>
                    </div>

                    <div id="collapsetwo" class="collapse show" aria-labelledby="headingtwo" data-parent="#accordionExample2">
                      <div class="card-body">
                      <ul >
                          <li class="list-unstyled"><i class="fas fa-spinner text-warning"></i> Adicionar filtros de consulta</li>
                          <li class="list-unstyled"><i class="fas fa-spinner text-warning"></i> Adicionar opção para alteração dos registros</li>
                          <li class="list-unstyled"><i class="fas fa-spinner text-warning"></i> Adicionar niveis de acesso</li>
                          <li class="list-unstyled"><i class="fas fa-spinner text-warning"></i> Adicionar data de nascimento no cadastro</li>
                          <li class="list-unstyled"><i class="fas fa-spinner text-warning"></i> Adicionar icones de despesas e ganhos </li>
                          <li class="list-unstyled"><i class="fas fa-spinner text-warning"></i> Adicionar foto de usuário</li>
                          <li class="list-unstyled"><i class="fas fa-spinner text-warning"></i> Refactory de arquivo layout para evitar redundância de código</li>
                          <li class="list-unstyled"><i class="fas fa-spinner text-warning"></i> Adicionar paginação nas consultas</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                <div class="card">
  
                </div>
                  
              </div>
                
            </div>
        </div>
      </div>
    </section>

    



   
    <footer class="mt-4 mb-4">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <nav class="navbar navbar-expand-sm ">
              <ul class="text-dark" style="list-style: none;">
                <li>
                  <a href="#" class="nav-link text-dark">Home</a>
                </li>
                <li>
                  <a href="#" class="nav-link text-dark">Recursos</a>
                </li>
              </ul>
            </nav>
          </div>

          <div class="col-md-4  d-flex ">
            <div class="align-self-auto">
                  <a href="" class="btn btn-outline-dark">
                    <i class="fab fa-facebook fa-2x"></i>
                  </a>
                  <a href="" class="btn btn-outline-dark">
                    <i class="fab fa-twitter fa-2x"></i>
                  </a>
                  <a href="" class="btn btn-outline-dark">
                    <i class="fab fa-instagram fa-2x"></i>
                  </a>
                  <a href="" class="btn btn-outline-dark">
                    <i class="fab fa-youtube fa-2x"></i>
                  </a>
            </div>
          </div>
        </div>
        
      </div>
      
    </footer>

    <!-- JavaScript (Opcional) -->
    <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<?php
  
?>