<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>Projeto Finans</title>

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

        <!-- Estilo customizado -->
        <link rel="stylesheet" type="text/css" href="/public/css/estilo.css">


        <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

        <!-- foto aba -->
        <link rel="shortcut icon" href="/img/logo2.png" type="image/x-icon">
        

        


    </head>
    <body>
        <?= $this->content() ?>
        
        <!-- Gráficos Google-->,
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
        
        <script>
            //puxar as variaveis do php para fazer a incusão na página
            google.charts.load('current', {'packages':['bar']});
            google.charts.setOnLoadCallback(drawChart);

            function drawChart() {
                var data = google.visualization.arrayToDataTable([
                ['', 'Ganhos', 'Despesas'],
                ['Ganhos x Despesas', <?= $this->view->somaValorGanho['soma'] ?>, <?= $this->view->somaValor['soma'] ?>],
                
                ]);

                var options = {
                chart: {
                    subtitle: 'Seu saldo é de R$ <?= $this->view->somaValorGanho['soma'] - $this->view->somaValor['soma'] ?>,00 ',
                },
                bars: 'vertical',
                vAxis: {format: 'decimal'},
                height: 300,
                colors: ['#2F4F4F', '#FFD700']
                };

                var chart = new google.charts.Bar(document.getElementById('columnchart_material'));

                chart.draw(data, google.charts.Bar.convertOptions(options));
            }

        </script>
        <?php 
        
        $transporte_nome =  isset($this->view->totalPorCategoria[0]['descricao']) ? $this->view->totalPorCategoria[0]['descricao'] : 'Valor Não Computado' ;
        $transporte_valor =  isset($this->view->totalPorCategoria[0]['soma']) ? $this->view->totalPorCategoria[0]['soma'] : 1 ;

        $alimentacao_nome =  isset($this->view->totalPorCategoria[1]['descricao']) ? $this->view->totalPorCategoria[1]['descricao'] : 'Valor Não Computado';
        $alimentacao_valor =  isset($this->view->totalPorCategoria[1]['soma']) ? $this->view->totalPorCategoria[1]['soma'] : 1;

        $lazer_nome =  isset($this->view->totalPorCategoria[2]['descricao']) ? $this->view->totalPorCategoria[2]['descricao'] : 'Valor Não Computado' ;
        $lazer_valor =  isset($this->view->totalPorCategoria[2]['soma']) ? $this->view->totalPorCategoria[2]['soma'] : 1;

        $saude_nome =  isset($this->view->totalPorCategoria[3]['descricao']) ? $this->view->totalPorCategoria[3]['descricao'] : 'Valor Não Computado';
        $saude_valor =  isset($this->view->totalPorCategoria[3]['soma']) ? $this->view->totalPorCategoria[3]['soma'] : 1 ;

        $educacao_nome =  isset($this->view->totalPorCategoria[4]['descricao']) ? $this->view->totalPorCategoria[4]['descricao'] : 'Valor Não Computado';
        $educacao_valor =  isset($this->view->totalPorCategoria[4]['soma']) ? $this->view->totalPorCategoria[4]['soma'] : 1 ;

        ?>

        <script>

                google.charts.load('current', {'packages':['corechart']});

                // Set a callback to run when the Google Visualization API is loaded.
                google.charts.setOnLoadCallback(drawChart);

                // Callback that creates and populates a data table,
                // instantiates the pie chart, passes in the data and
                // draws it.
                function drawChart() {

                // Create the data table.
                var data = new google.visualization.DataTable();
                data.addColumn('string', 'Topping');
                data.addColumn('number', 'Slices');
                data.addRows([
                /*transporte*/
                ['<?= $transporte_nome ?>', <?= $transporte_valor ?>],
                /*alimentação*/
                ['<?= $alimentacao_nome ?>', <?= $alimentacao_valor ?>],
                /*lazer*/
                ['<?= $lazer_nome ?>', <?= $lazer_valor ?>],
                /*saúde*/
                ['<?= $saude_nome ?>', <?= $saude_valor ?>],
                /*educação*/
                ['<?= $educacao_nome ?>', <?= $educacao_valor?>],
                ]);


                // Set chart options
                var options = {
                'title':'',
                'width':600,
                'height':400,

                }


                // Instantiate and draw our chart, passing in some options.
                var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
                chart.draw(data, options);
}
        </script>
    </body>
</html>